Update README.md
wakayama-kazuma/dateplaner pull request #3
Opened 2024-06-11 06:43 UTC by wakayama-kazuma

卒業制作README

2024-06-11 09:10 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
以下コメントになります。

---

■技術スタック
・使用予定の技術スタックをREADMEに記載してください。

■データ
・穴場スポットのデータをどのように最初集めるのかをREADMEに記載してください。ご自身で30個データを登録するでもOKです。（理由：デートプランを作成するのに、穴場スポットのデータはある程度必要かと考えたため）

■プラン
・プランはどのように練ったり、作成したりするのかのイメージが文面からは想像が難しかったため、具体的にどんな風に使用すると、ユーザーはそれらを利用できるのかを、読み手にユーザーがサービスを使用する姿が浮かんでくるように説明をREADMEに記載してください。

2024-06-13 06:08 UTC, wakayama-kazuma commented
コメントありがとうございます。
以下記入しました。
■技術スタック
## ■技術スタック
 バックエンド
* Ruby on Rails
* Node.js

フロントエンド
* CSS tailwind

デプロイ
* Heroku

データベース
* PostgreSQL
* AWS

API
* Google Maps API

■データ
・穴場スポットのデータに関しては自身や周りの情報をもとに30ほど入れておく

■プラン
・ユーザーフロー
1. ユーザーにログイン（登録）してもらう、
2. ユーザーが訪れたいスポットを検索・選択
3. スポットの訪問順序と滞在時間を設定(移動手段)
5. スポット間のルートがGoogle Maps上に表示
6. 各ルートの移動時間、距離を確認

2024-06-13 10:27 UTC, tarakish requested changes
修正確認しました。
以下コメントです！

---
■技術スタック
データベースはAWSのどのサービスを使うかまで記載しておきましょう！

■機能候補
MVPリリースの内容が多い印象を受けました。
このサービスの価値は何になるのか、差別化ポイントなどから考えて、その価値を提供できる最低限の機能まで絞り込めると良いと思います。

2024-06-14 03:25 UTC, wakayama-kazuma commented
確認ありがとうございます。
以下修正しました。

■技術スタック
AWS（Amazon RDS）
■機能候補
MVPリリース
簡易ログイン・ログアウト機能
デート、穴場スポット新規登録・編集機能
キーワード検索機能
モデルコース新規作成・編集機能
スポットごとの滞在時間・移動手段設定機能
いいね機能
お気に入り機能・お気に入り一覧
Twitter共有機能
一日のスケジュールをタイムライン形式で表示
本リリース
パスワード再設定機能
ユーザー登録機能
ログイン・ログアウト機能
Googleアカウントログイン・ログアウト機能
プロフィール表示・編集機能
自分の投稿履歴機能
オートコンプリート検索・絞り込み検索機能

2024-06-14 05:37 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。

2024-06-25 06:03 UTC, wakayama-kazuma commented
画面遷移図完了

2024-06-25 06:09 UTC, Tsuchiya2 commented
画面遷移図もですが、別途それぞれプルリクエスト・issueを作成してレビュー依頼を出してください。
よろしくお願いいたします。

2024-06-25 08:34 UTC, closed without merging